package com.patson

object DemandConstants {
  /**
   * min distance is used in two contexts:
   * 1) find nearby domestic between minDistance and 4x minDistance
   *    - default catchment is 1400km (350 * 4)
   * 2) reduce demand under minDistance (if not island or high affinity)
   */
  val localityMinDistanceMap = Map(
    "default" -> 350,
    "CA" -> 400,
    "US" -> 400,
    "DO" -> 100,
    "HT" -> 100,
    "BZ" -> 100,
    "HN" -> 100,
    "CR" -> 100,
    "GT" -> 100,
    "NI" -> 200,
    "HN" -> 200,
    "PA" -> 200,
    "CO" -> 200,
    "PE" -> 250,
    "BR" -> 325,
    "AR" -> 350,
    "ET" -> 210,
    "KE" -> 220,
    "TZ" -> 220,
    "ZW" -> 220,
    "ZA" -> 300,
    "IS" -> 100,
    "GB" -> 400,
    "ES" -> 275, //Make traveler stay within Canaries
    "NL" -> 400,
    "BE" -> 450,
    "DE" -> 320,
    "CH" -> 300,
    "IT" -> 320,
    "PL" -> 400,
    "NO" -> 300,
    "SE" -> 400,
    "FI" -> 300,
    "RU" -> 375,
    "AE" -> 370,
    "BA" -> 370,
    "QA" -> 370,
    "IQ" -> 50, //turn EBL into an island
    "NP" -> 100,
    "CN" -> 700, //HSR rail
    "TW" -> 220,
    "JP" -> 400,
    "KR" -> 360,
    "AU" -> 360,
  )
  val localityAdjustMap = Map(
    "AO" -> 1.8,
    "BI" -> 2.1,
    "BF" -> 1.9,
    "BJ" -> 2.2,
    "BW" -> 2.1,
    "CD" -> 1.4,
    "CG" -> 1.6,
    "CI" -> 1.6,
    "CM" -> 1.8,
    "CV" -> 1.8,
    "DJ" -> 2.1,
    "EG" -> 0.9,
    "ER" -> 1.9,
    "ET" -> 2.4,
    "GA" -> 2.1,
    "GH" -> 2.1,
    "GM" -> 2.1,
    "GN" -> 1.6,
    "GW" -> 1.6,
    "GQ" -> 2.2,
    "KE" -> 2.1,
    "KM" -> 2.1,
    "LR" -> 1.7,
    "LS" -> 2.4,
    "ML" -> 1.7,
    "MR" -> 1.7,
    "MG" -> 1.6,
    "MU" -> 2.0,
    "MW" -> 2.1,
    "MZ" -> 1.9,
    "NA" -> 2.3,
    "NE" -> 1.7,
    "NG" -> 1.2,
    "SC" -> 2.2,
    "SD" -> 1.7,
    "SL" -> 2.4,
    "SN" -> 2.4,
    "SO" -> 1.5,
    "SS" -> 1.6,
    "ST" -> 2.1,
    "SZ" -> 2.1,
    "TD" -> 1.6,
    "TG" -> 1.6,
    "TZ" -> 1.9,
    "UG" -> 1.4,
    "ZA" -> 2.1,
    "ZM" -> 1.7,
    "ZW" -> 1.6,

    "AR" -> 1.4,
    "BO" -> 2.2,
    "BZ" -> 2.5,
    "BR" -> 1.2,
    "CL" -> 2.8,
    "CO" -> 1.8,
    "CR" -> 2.0,
    "EC" -> 2.4,
    "GY" -> 2.0,
    "HN" -> 2.0,
    "PE" -> 2.7,
    "PA" -> 3.8,
    "PY" -> 2.0,
    "SV" -> 2.0,
    "UY" -> 2.0,

    "AE" -> 2.0,
    "BA" -> 1.8,
    "BD" -> 0.8,
    "CN" -> 0.7,
    "HK" -> 1.2,
    "KR" -> 1.9,
    "ID" -> 1.4,
    "IL" -> 1.4,
    "IN" -> 0.45,
    "IR" -> 1.8,
    "LK" -> 1.2,
    "JP" -> 1.1,
    "KW" -> 2.6,
    "MY" -> 1.8,
    "NP" -> 1.7,
    "OM" -> 1.6,
    "PH" -> 1.5,
    "PK" -> 0.6,
    "SA" -> 1.9,
    "SG" -> 1.9,
    "TH" -> 1.0,
    "TR" -> 1.3,
    "TW" -> 1.7,
    "VN" -> 1.7,

    "AU" -> 1.3,
    "NZ" -> 1.9,

    "AL" -> 1.3,
    "AT" -> 1.1,
    "BE" -> 1.1,
    "CH" -> 1.8,
    "CY" -> 1.3,
    "CZ" -> 1.2,
    "DE" -> 1.0,
    "DK" -> 1.2,
    "ES" -> 1.1,
    "FI" -> 1.3,
    "FR" -> 0.8,
    "GB" -> 1.4,
    "GR" -> 1.3,
    "HU" -> 1.2,
    "IE" -> 1.3,
    "IS" -> 1.3,
    "IT" -> 1.2,
    "LU" -> 1.3,
    "MT" -> 1.9,
    "NL" -> 1.0,
    "NO" -> 1.0,
    "PL" -> 1.0,
    "PT" -> 1.5,
    "RO" -> 0.7,
    "RS" -> 1.4,
    "RU" -> 0.8,
    "SE" -> 1.1,

    "BM" -> 1.8,
    "BS" -> 1.3,
    "CA" -> 1.3,
    "DO" -> 1.7,
    "JM" -> 1.4,
    "MX" -> 1.0,
    "PR" -> 1.5,
    "TT" -> 1.2,
    "US" -> 1.0
  )

  val HEAVY_RAIL_LINKS = List(
    ("LHR","LBA"),
    ("LHR","MME"),
    ("LHR","NCL"),
    ("STN","MAN"),
    ("LTN","MAN"),
    ("LGW","CDG"),
    ("STN","CDG"),
    ("LGW","ORY"),
    ("STN","ORY"),
    ("LHR","BRU"),
    ("LHR","EIN"),
    ("LHR","RTM"),
    ("LGW","EIN"),
    ("LGW","RTM"),
    ("LCY","RTM"),
    ("LHR","LIL"),
    ("XCR","SXB"),
    ("CDG","LYS"),
    ("ORY","LYS"),
    ("CDG","BOD"),
    ("ORY","BOD"),
    ("CDG","SXB"),
    ("ORY","SXB"),
    ("CDG","BSL"),
    ("ORY","BSL"),
    ("CDG","NTE"),
    ("ORY","NTE"),
    ("CDG","RNS"),
    ("ORY","RNS"),
    ("LYS","BCN"),
    ("MRS","BCN"),
    ("ORY","GVA"),
    ("MRS","GVA"),
    ("CDG","BRU"),
    ("ORY","BRU"),
    ("CDG","EIN"),
    ("ORY","EIN"),
    ("AMS","BRU"),
    ("AMS","CGN"),
    ("AMS","DUS"),
    ("ANR","AMS"),
    ("ANR","RTM"),
    ("LUX","RTM"),
    ("LUX","CDG"),
    ("LUX","ORY"),
    ("LUX","BRU"),
    ("BRU","CGN"),
    ("CRL","FRA"),
    ("FRA","CGN"),
    ("FRA","DUS"),
    ("FRA","STR"),
    ("FRA","BSL"),
    ("MUC","STR"),
    ("BER","HAM"),
    ("MAD","SVQ"),
    ("MAD","VLC"),
    ("MAD","AGP"),
    ("MAD","ZAZ"),
    ("FCO","BLQ"),
    ("FCO","FLR"),
    ("FCO","NAP"),
    ("FCO","PSA"),
    ("TRN","VCE"),
    ("LIN","VCE"),
    ("ZRH","LUG"),
    ("GVA","MXP"),
    ("MUC","NUE"),
    ("FRA","NUE"),
    ("BER","NUE"),
    ("VIE","NUE"),
    ("VIE","SZG"),
    ("VIE","INN"),
    ("VIE","BUD"),
    ("VIE","PRG"),
    ("MMX","GOT"),
    ("OSL","GOT"),
    ("NRT","ITM"),
    ("NRT","KIX"),
    ("HND","NGO"),
    ("HND","SDJ"),
    ("FSZ","ITM"),
    ("FSZ","KIX"),
    ("FSZ","NRT"),
    ("FSZ","SDJ"),
    ("FSZ","UKB"),
    ("NJA","ITM"),
    ("NJA","KIX"),
    ("NJA","NGO"),
    ("NJA","SDJ"),
    ("NJA","UKB"),
    ("NRT","SDJ"),
    ("AOJ","SDJ"),
    ("AOJ","HNA"),
    ("ITM","OKJ"),
    ("KIX","OKJ"),
    ("HND","TOY"),
    ("NRT","TOY"),
    ("ITM","NOG"),
    ("KIX","FUK"),
    ("FUK","KOJ"),
    ("TPE","KHH"),
    ("TPE","TNN"),
    ("TPE","TXG"),
    ("TSA","TNN"),
    ("KHH","TSA"),
    ("SHA","NKG"),
    ("SHA","HGH"),
    ("CTU","CKG"),
    ("PEK","TSN"),
    ("JFK","BDI"),
    ("JFK","BOS"),
    ("JFK","PVD"),
    ("JFK","BWI"),
    ("EWR","DCA"),
    ("EWR","BWI"),
    ("EWR","PVD"),
    ("HVN","BWI"),
    ("HVN","BOS"),
    ("MDT","JFK"),
    ("MDT","EWR"),
    ("MDT","LGA"),
    ("JED","MED")
  )

  def doesPairExist(s1: String, s2: String, lookupSet: Set[(String, String)]): Boolean = {
    val lookupTuple = if (s1 < s2) (s1, s2) else (s2, s1)
    lookupSet.contains(lookupTuple)
  }

  val railLookupSet: Set[(String, String)] = HEAVY_RAIL_LINKS.map {
    case (a, b) if a < b => (a, b)
    case (a, b)          => (b, a)
  }.toSet


}
